### ISSUE TITLE
Search for other datasets (that also contain disambiguation)

### ISSUE THREAD

**Issue by aksenyuk** [aksenyuk/visual-wsd#2]

**Comment by alessandro1802** [comment]
https://www.kaggle.com/datasets/elkamel/corel-images
A 10 concept groups of images composed each by 100 images (1000 images in total).
http://kobus.ca/research/publications/03/LWM-03/LWM-03.pdf

**Comment by alessandro1802** [comment]
https://github.com/google-research-datasets/wit
WIT is composed of a curated set of 37.6 million entity rich image-text examples with 11.5 million unique images across 108 Wikipedia languages.
