### ISSUE TITLE
Research unsupervised solutions (read description)

### ISSUE THREAD

**Issue by aksenyuk** [aksenyuk/visual-wsd#4]
- Train model on general pictures
- Check if it works for ambiguous photos as well

**Comment by alessandro1802** [comment]
Vision Meets Definitions: Unsupervised Visual Word Sense Disambiguation Incorporating Gloss Information
https://aclanthology.org/2023.acl-long.88.pdf

**Comment by alessandro1802** [comment]
One idea is to fine tune [BLIP](https://github.com/salesforce/BLIP/tree/main) model to fit out needs.
